version: '3'                                                                                                                                                                                                                    

services:                                                                                                                                                                                                                       
  influxdb:                                                                                                                                                                                                                     
    image: influxdb                                                                                                                                                                                                             
    container_name: influxdb                                                                                                                                                                                                
    restart: unless-stopped
    ports:                                                                                                                                                                                                                      
      - ${INFLUXDB_PORT}:8086                                                                                                                                                                                                             
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    # run "id -u" at command line, then uncomment next line 
    user: ${USER_ID}
    volumes:                                                                                                                                                                                                                    
      - ./data:/var/lib/influxdb2:rw                                                                                                                                                                                        
      - ./config:/etc/influxdb2:rw                                                                                                                                                                                              
                                                        
  grafana:
    image: grafana/grafana-enterprise                                                                                                                                                                                                      
    container_name: grafana                                                                                                                                                                                                     
    restart: unless-stopped
    depends_on:                                                                                                                                                                                                                 
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SECURITY_ADMIN_EMAIL=${GF_SECURITY_ADMIN_EMAIL}
      - INFLUXDB_HOST=${INFLUXDB_IP}
      - INFLUXDB_PORT=${INFLUXDB_PORT}
      - INFLUXDB_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - INFLUXDB_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - INFLUXDB_DEFAULT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      # some solar info plugs
      - GF_INSTALL_PLUGINS=${GF_PLUGINS}
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_PANELS_DISABLE_SANITIZE_HTML=true

    ports:                                                                                                                                                                                                                      
      - ${GRAFANA_PORT}:3000                                                                                                                                                                                                             
    # run "id -u" at command line, then uncomment next line 
    user: ${USER_ID}
    volumes:                                                                                                                                                                                                                    
      - ./gdata:/var/lib/grafana:rw
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    
  weather411:
      image: jasonacox/weather411:0.2.3
      container_name: weather411
      hostname: weather411
      restart: unless-stopped
      user: "${PWD_USER:-1000:1000}"
      volumes:
          - type: bind
            source: ./weather
            target: /var/lib/weather
            read_only: true
      ports:
          - "${WEATHER411_PORTS:-8676:8676}"
      environment:
          - WEATHERCONF=/var/lib/weather/weather411.conf
      depends_on:
          - influxdb

  telegraf:
    image: telegraf
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
    #  - DOCKER_INFLUXDB_INIT_MODE=setup
    #  - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
    #  - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
    #  - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_BUCKET=SNMP_2
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      # Mount for telegraf config
      - ./mytelegraf.conf:/etc/telegraf/telegraf.conf:ro
      # Get MIBS: https://stangneth.com/2021/07/15/grafana-influxdb-telegraf-mit-docker-compose/#Telegraf_is_not_detecting_SNMP_Mibs_correctly
      # e.g. git clone https://github.com/librenms/librenms.git
      # cd /mibs/librenms/mibs
      # cp . ./mibs
      # Needs to be retrieved for this to work
      - ./mibs:/usr/share/snmp/mibs:rw

